import React from 'react';
import Header from '../components/header.js'
import Layout from '../components/Layout.js'

import { useEffect, useState } from 'react'
import Link from 'next/link'

/*export default function Articles() {
    return (
        <div>

            <Header />
            <article>
                <h2>Article 1: Lorem Ipsum</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in nunc sit amet turpis volutpat hendrerit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla, sunt incidunt possimus ullam maiores quisquam quibusdam perferendis sapiente eius nam quae vero magni perspiciatis laboriosam fugit deleniti quas velit! Incidunt?</p>
            </article>

            <article>
                <h2>Article 2: Sample Article</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in nunc sit amet turpis volutpat hendrerit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla, sunt incidunt possimus ullam maiores quisquam quibusdam perferendis sapiente eius nam quae vero magni perspiciatis laboriosam fugit deleniti quas velit! Incidunt?</p>
            </article>

            <article>
                <h2>Article 3: Placeholder Text</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in nunc sit amet turpis volutpat hendrerit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla, sunt incidunt possimus ullam maiores quisquam quibusdam perferendis sapiente eius nam quae vero magni perspiciatis laboriosam fugit deleniti quas velit! Incidunt?</p>
            </article>
        </div>
    );
}*/


export default function Articles() {
    const [articles, setArticles] = useState([])

    useEffect(() => {
        async function fetchData() {
            const response = await fetch('/api/articles')
            const articles = await response.json()
            setArticles(articles)
        }
        fetchData()
    }, [])

    return (
        <Layout
            title="Articles"
            description="Generated by create next app"
        >
            <h1 className='wt-title'>
                Web technologies articles
            </h1>
            <p className="italic font-bold my-5">This page fetch data from the client side, not good for SEO.</p>
            <ul>
                {articles.map(article => (
                    <li key={article.slug} className="my-5">
                        <h2 className="font-bold mb-1">
                            <Link href={`/articles/${article.slug}`}>{article.title}</Link>
                        </h2>
                        <p>{article.message}</p>
                    </li>
                ))}
            </ul>
        </Layout>
    )
}
