import { useState } from 'react';
import Layout from '../components/Layout.js';
import UserContext from '../components/UserContext'
import { useContext } from 'react';

export default function Page() {
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [contactMessage, setContactMessage] = useState('');
  const [confirmationMessage, setConfirmationMessage] = useState(null);

  const { supabase } = useContext(UserContext);


  const onSubmit = async (e) => {
    e.preventDefault();

    const { data, error } = await supabase.from('contacts').insert([
      { firstname: firstName, lastname: lastName, email: email, message: contactMessage }
    ]);

    if (error) {
      console.error('Error inserting record:', error.message);
      setConfirmationMessage('Error inserting record: ' + error.message);
    } else {
      console.log('Record inserted successfully:', data);
      setFirstName('');
      setLastName('');
      setEmail('');
      setContactMessage('');

      setConfirmationMessage('We will contact you !');
    }
  };

  return (
    <Layout
      title="Contacts"
      description="Generated by create next app"
    >
      <div className="container mx-auto px-4 py-8">
        <h1 className='text-4xl font-bold text-center mb-6'>
          Contacts
        </h1>
        <form className="max-w-lg mx-auto grid gap-6" onSubmit={onSubmit}>
          <div>
            <label className="block mb-2 text-sm font-medium">
              <span>First name</span>
              <input
                type="text"
                name="firstname"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                className="text-gray-700 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
              />
            </label>
          </div>
          <div>
            <label className="block mb-2 text-sm font-medium">
              <span>Last name</span>
              <input
                type="text"
                name="lastname"
                value={lastName}
                onChange={(e) => setLastName(e.target.value)}
                className="text-gray-700 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
              />
            </label>
          </div>
          <div>
            <label className="block mb-2 text-sm font-medium">
              <span>Email</span>
              <input
                type="text"
                name="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="text-gray-700 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
              />
            </label>
          </div>
          <div>
            <label className="block mb-2 text-sm font-medium">
              <span>Message</span>
              <textarea
                name="message"
                value={contactMessage}
                onChange={(e) => setContactMessage(e.target.value)}
                className="text-gray-700 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
              />
            </label>
          </div>
          <div>
            <button
              className="rounded-md py-2 px-4 text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50"
            >
              Send
            </button>
          </div>
        </form>
        {confirmationMessage &&
          <div
            aria-label="Overflow below the drawer dialog"
            className="fixed inset-0 bg-black/80 flex items-center justify-center p-4"
            onClick={() => setConfirmationMessage(null)}
            role="dialog"
          >
            <div
              aria-label="Alert pane"
              className="rounded-md shadow-lg max-h-[90vh] max-w-[95vw] overflow-auto bg-white p-6"
            >
              <p className="text-lg text-gray-800">{confirmationMessage}</p>
            </div>
          </div>
        }
      </div>
    </Layout>
  );
}
